### ISSUE TITLE
Security logs does not work

### ISSUE THREAD

**Issue by JosueGordon** [fsegurai/TEKKB_Management_Issues#4]
Security logs does not show real data

![image](https://user-images.githubusercontent.com/31802709/228905139-f9b11e35-a972-4800-b1a4-e00d9aaf6426.png)

**Comment by fsegurai** [comment]
It is currently being worked, hopefully this feature will be release on Q2

**Comment by fsegurai** [comment]
This module has been fixed and released in a preview version. You can now search for any visible data in the search input and export it in different formats (CSV, JSON, TXT, YAML and XML)

![image](https://github.com/fsegurai/TEKKB_Management_Issues/assets/42953884/a56c53c2-a892-4a10-ab79-30a1f87366c5)
