### ISSUE TITLE
Language setting does not work

### ISSUE THREAD

**Issue by JosueGordon** [fsegurai/TEKKB_Management_Issues#5]
![image](https://user-images.githubusercontent.com/31802709/228905446-82ffafbd-c751-4963-bd06-82bd96da0b10.png)

**Comment by fsegurai** [comment]
Language selection and the rest of the accessibility settings are now operational.
![image](https://user-images.githubusercontent.com/42953884/236598133-84ce2bf8-5c19-4ff8-ad5c-e6544db31f24.png)

The fix will be release during Q2
